server:
  port: 6062
spring:
  application:
    name: hello-service
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka